### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by 2515299122** [WellFine/accounting#1]
[ miniprogram/components/index/dataInfo/header/header.json 文件内容错误] miniprogram/components/index/dataInfo/header/header.json: ["usingComponents"]["mp-icon"]: "weui-miniprogram/icon/icon" 未找到(env: Windows,mp,1.05.2111300; lib: 2.19.1)

Uncaught FrameworkError 
 Unexpected token '<' 
 SyntaxError: Unexpected token '<'(env: Windows,mp,1.05.2111300; lib: 2.19.1)

**Comment by WellFine** [comment]
重新copy一份试试看

**Comment by Mrkk1** [comment]
您好 云数据库需要创建那些表和哪些字段呀

**Comment by WellFine** [comment]
这个版本只有一个 account 表，字段如下：

```js
{
  _id: String,
  _openid: String,
  account: String,
  how: String,
  money: Number,
  name: String,
  py: String,
  remark: String,
  sub: String,
  time: TimeStamp,
  type: Number
}
```
